# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
- develop
- features/*

pool:
  vmImage: 'windows-latest'

container: mcr.microsoft.com/dotnet/core/sdk:3.0

# Define variables
variables:
-template

# Scheule to run
schedules:
-cron: "00 09 ** 1"
displayname:"weekly Credscan build"
branches:
include:
-master:
always: true

steps:
- task: DotNetCoreCLI@2
  inputs: 
    command: build
    

- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: '**/*Tests*.csproj'
